### PR TITLE
Combined the tilesets in stage_road1.tscn

### PR DESCRIPTION
**Pull request by ghost**
The three tilesets in stage_road1.tscn only contained
one tile each. I've taken these three tilesets and
replaced them with a single tileset that contains
all the tiles in one.

This results in a prettier node hierarchy in the
scene as well as making editing easier if the
layout of tiles needs to be changed.

### CODE REVIEW

**Comment by Anatolij-Grigorjev** [comment]
Hey!

Yeah, I was well aware of the limitations when categorising tiles like this when I had to make separate tilesets for every tile. I'll be the first to say its not the fun or convenient way of doing anything, but this was actually done to work around an engine limitation - Godot cant have different collision layers for different tiles in the same tileset. 
My experiments show me that this is because whatever collision layers you set on your tile colliders before exporting them into a tilemap are ignoren on the scene that instantiates the tilemap (maybe that info just isnt even baked into the map), so you can have one collision configuration per tilemap max.
For me this mean dividing the tiles by collision type - a tileset for roads, tileset for sidwalks and a tileset for curbs. 
The second thing is a design choice made based in this existing separation - when the player presses Space or whatever is setup to mount/dismount moped, the active rebel node searches the closest vertical global position on a target tileset. Unless I hardcode some kinds of mappings myself, I dont really know of a way to do that sort of thing when all the tiles belong to a single tileset. The idea here is to dynamically animate the node, let the dismounting walking animation play till rebel reaches sidewalk, or mounting walking animation till he goes down the road (animations arent made yet, but I hope this textual explanation is visual enough to get what I mean)

In its current state, this PR would organize the singular tileset for me, but I dont have any good solutions for the 2 main problems outlines above. If you think there is some way to solve this while keeping a single tileset, im definitely open to suggestions, my own solutions so far have been quite MVP.

**Comment by ghost** [comment]
Ah I see! Off the top of my head, I can think of a few ways to solve those issues. I'll work on it a little later.

**Comment by ghost** [comment]
I've updated the branch to support the multiple collision layers in tilemaps while still allowing you to only need to edit one single map. As far as I can tell, all features are working properly. Lemme know if there are still any problems.

**Comment by Anatolij-Grigorjev** [comment]
I tried these variations and can honestly say this seems to work as expected and should simplify tileset editing!
With my rookie understanding of Godot design I wouldn't have considered a solution like this, I'll keep this in mind for future things.

Thanks a lot! I suppose actual level sizes will tell if this has problems of scaling, but I dont expect bigger problems than having the tilesets separately loaded when the whole thing starts up anyway

**Pull request merged**
